
SELECT YEAR(SALES_DATE) YEAR, MONTH(SALES_DATE) MONTH, COUNT(DISTINCT O.USER_ID) PURCHASED_USER, ROUND(COUNT(DISTINCT O.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = "2021"),1) PURCHSE_RATIO
FROM USER_INFO U , ONLINE_SALE O
WHERE YEAR(U.JOINED) = "2021"
AND U.USER_ID = O.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE);


# SELECT YEAR, SUBSTR(MONTH,2,1) MONTH, COUNT(USER_ID) PUCHASED_USERS, ROUND(COUNT(USER_ID) / (SELECT COUNT(USER_ID)
#                         FROM USER_INFO
#                         WHERE SUBSTR(JOINED, 1, 4) = "2021"), 1) PURCHASED_RATIO
# FROM (
#     SELECT SUBSTR(SALES_DATE, 1, 4) YEAR, SUBSTR(SALES_DATE, 6, 2) MONTH, USER_ID
#     FROM ONLINE_SALE
#     WHERE USER_ID IN ( SELECT USER_ID 
#                         FROM USER_INFO
#                         WHERE SUBSTR(JOINED, 1, 4) = "2021" )
#     GROUP BY SUBSTR(SALES_DATE, 1, 4), SUBSTR(SALES_DATE, 6, 2), USER_ID ) C
# GROUP BY YEAR, MONTH
# ORDER BY YEAR, MONTH;