
SELECT BT.AUTHOR_ID, A.AUTHOR_NAME, BT.CATEGORY, SUM(BT.TOTAL_SALES)
FROM
    (SELECT BS.BOOK_ID, B.CATEGORY, B.AUTHOR_ID, SUM(SALES) * B.PRICE AS TOTAL_SALES
    FROM BOOK B, BOOK_SALES BS
    WHERE B.BOOK_ID = BS.BOOK_ID
     AND DATE_FORMAT(BS.SALES_DATE, '%y-%m') = "22-01"
    GROUP BY BOOK_ID) BT, AUTHOR A
WHERE BT.AUTHOR_ID = A.AUTHOR_ID
GROUP BY BT.AUTHOR_ID, BT.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;