SELECT A.HISTORY_ID,
        TRUNCATE(A.DAILY_FEE * A.DATEDIFF * IFNULL(1-B.DISCOUNT_RATE/100, 1),0) FEE
FROM
    (SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, DATEDIFF(H.END_DATE, H.START_DATE)+1 DATEDIFF, H.HISTORY_ID HISTORY_ID,
            CASE
            WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 < 7 THEN 0
            WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 < 30 THEN 7
            WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 < 90 THEN 30
            ELSE 90 END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    WHERE C.CAR_TYPE = "트럭"
    AND C.CAR_ID = H.CAR_ID) A
    LEFT JOIN 
            (SELECT SUBSTRING_INDEX(DURATION_TYPE, "일", 1) DURATION_TYPE, DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE CAR_TYPE = "트럭") B
    ON A.DURATION_TYPE = B.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC;

# SELECT *
# FROM (SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, DATEDIFF(H.END_DATE, H.START_DATE)+1 DATEDIFF, H.HISTORY_ID HISTORY_ID,
#             CASE
#             WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 < 7 THEN 0
#             WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 < 30 THEN 7
#             WHEN DATEDIFF(H.END_DATE, H.START_DATE)+1 < 90 THEN 30
#             ELSE 90 END AS DURATION_TYPE
#     FROM CAR_RENTAL_COMPANY_CAR C, CAR_RENTAL_COMPANY_RENTAL_HISTORY H
#     WHERE C.CAR_TYPE = "트럭"
#     AND C.CAR_ID = H.CAR_ID) A
#     LEFT JOIN 
#             (SELECT SUBSTRING_INDEX(DURATION_TYPE, "일", 1) DURATION_TYPE, DISCOUNT_RATE
#             FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#             WHERE CAR_TYPE = "트럭") B
#     ON A.DURATION_TYPE = B.DURATION_TYPE;

# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_CAR C
# WHERE H.CAR_ID = C.CAR_ID
# AND C.CAR_TYPE="트럭";

# SELECT *
# FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN;