SELECT USER_ID, NICKNAME, TOTAL
FROM USED_GOODS_USER A
JOIN 
    (SELECT WRITER_ID, SUM(PRICE) TOTAL
    FROM USED_GOODS_BOARD
     WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
    HAVING SUM(PRICE) >= 700000) B
ON A.USER_ID = B.WRITER_ID
ORDER BY B.TOTAL;

