
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, (CNT * FP.PRICE) TOTAL
    FROM FOOD_PRODUCT FP, ( SELECT PRODUCT_ID, SUM(AMOUNT) CNT
                            FROM FOOD_ORDER
                            WHERE SUBSTR(PRODUCE_DATE, 1, 7) = "2022-05"
                            GROUP BY PRODUCT_ID ) FO
    WHERE FP.PRODUCT_ID = FO.PRODUCT_ID
    ORDER BY TOTAL DESC, PRODUCT_ID